version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - SECRET_KEY=5MYVjL3tVDMjBFlKOSt5lYzVM1KTF8oq
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=fastapi
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: